/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.aula.interfaceia;

import java.awt.*;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.json.JSONArray;
import org.json.JSONObject;

/**
 *
 * @author lucas
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dimension.width - this.getWidth()) / 2;
        int y = (dimension.height - this.getHeight()) / 2;
        this.setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel = new javax.swing.JPanel();
        PainelNomes = new javax.swing.JPanel();
        LabelNomes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NomesTextArea = new javax.swing.JTextArea();
        BotaoDescobrir = new javax.swing.JButton();
        LabelRespostas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        RespostasTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Interface TI");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setResizable(false);

        LabelNomes.setText("Nomes");

        NomesTextArea.setColumns(20);
        NomesTextArea.setRows(2);
        jScrollPane1.setViewportView(NomesTextArea);

        javax.swing.GroupLayout PainelNomesLayout = new javax.swing.GroupLayout(PainelNomes);
        PainelNomes.setLayout(PainelNomesLayout);
        PainelNomesLayout.setHorizontalGroup(
            PainelNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNomesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelNomesLayout.createSequentialGroup()
                        .addComponent(LabelNomes)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        PainelNomesLayout.setVerticalGroup(
            PainelNomesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelNomesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelNomes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BotaoDescobrir.setText("Descobrir");
        BotaoDescobrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoDescobrirMouseClicked(evt);
            }
        });
        BotaoDescobrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDescobrirActionPerformed(evt);
            }
        });

        jLabel2.setText("Respostas");

        RespostasTextArea.setEditable(false);
        RespostasTextArea.setColumns(20);
        RespostasTextArea.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        RespostasTextArea.setLineWrap(true);
        RespostasTextArea.setRows(5);
        RespostasTextArea.setEnabled(false);
        jScrollPane2.setViewportView(RespostasTextArea);

        javax.swing.GroupLayout LabelRespostasLayout = new javax.swing.GroupLayout(LabelRespostas);
        LabelRespostas.setLayout(LabelRespostasLayout);
        LabelRespostasLayout.setHorizontalGroup(
            LabelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelRespostasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LabelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LabelRespostasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        LabelRespostasLayout.setVerticalGroup(
            LabelRespostasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LabelRespostasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelLayout = new javax.swing.GroupLayout(Painel);
        Painel.setLayout(PainelLayout);
        PainelLayout.setHorizontalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelNomes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoDescobrir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(LabelRespostas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PainelLayout.setVerticalGroup(
            PainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(PainelNomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoDescobrir)
                .addGap(18, 18, 18)
                .addComponent(LabelRespostas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoDescobrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDescobrirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoDescobrirActionPerformed

    private void BotaoDescobrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoDescobrirMouseClicked
        String nomes = NomesTextArea.getText();
        RespostasTextArea.setText("");
        
        if (nomes.equals("")) {
            RespostasTextArea.setText("Nada para descobrir!");
            return;
        }
        
        JSONObject data = new JSONObject();
        List<String> lista = new ArrayList<>();
        Map<String, String> dataMap = new HashMap<>();

        String[] listaNome = nomes.split(",");

        for (String nome : listaNome) {
            nome = nome.replace(" ", "");
            lista.add(nome);
        }

        if (!lista.isEmpty()) {
            data.put("nomes", lista);
        }

        System.out.println(data);
        String responseStr = post(data);
        
        JSONObject response = new JSONObject(responseStr);
        String responseData =response.get("names_by_gender").toString();
        
        String[] array = responseData.replace("{", "").replace("}", "").split(",");
        
        for (int i = 0; i < array.length; i++) {
              String[] temp = array[i].split(",");
              
              for (int j = 0; j < temp.length; j++) {
                  String[] temp2 = temp[j].split(":");
                  dataMap.put(temp2[0], temp2[1]);
                  //System.out.println(temp2[0] + " " + temp2[1]);
              }
        }
        
        String tempText = RespostasTextArea.getText();
        for (String key : dataMap.keySet()) {
            tempText = tempText + key + ": " + dataMap.get(key) + "\n";
        }
        
        RespostasTextArea.setText(tempText);

    }//GEN-LAST:event_BotaoDescobrirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    private static String post(JSONObject data) {
        URL url;
        HttpURLConnection connection = null;

        String targetURL = "https://interdisciplinar-prob-poo.herokuapp.com/naive_bayes";

        try {
            //Create connection
            url = new URL(targetURL);
            connection = (HttpURLConnection) url.openConnection();
            connection.setRequestMethod("POST");
            connection.setRequestProperty("Content-Type",
                    "application/json");

            connection.setRequestProperty("Content-Length", ""
                    + Integer.toString(data.toString().getBytes().length));

            connection.setUseCaches(false);
            connection.setDoInput(true);
            connection.setDoOutput(true);

            //Send request
            DataOutputStream wr = new DataOutputStream(
                    connection.getOutputStream());
            wr.writeBytes(data.toString());
            wr.flush();
            wr.close();

            //Get Response    
            InputStream is = connection.getInputStream();
            BufferedReader rd = new BufferedReader(new InputStreamReader(is));
            String line;
            StringBuffer response = new StringBuffer();
            while ((line = rd.readLine()) != null) {
                response.append(line);
                response.append('\r');
            }
            rd.close();
            return response.toString();

        } catch (Exception e) {
            e.printStackTrace();
            return null;

        } finally {
            if (connection != null) {
                connection.disconnect();
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoDescobrir;
    private javax.swing.JLabel LabelNomes;
    private javax.swing.JPanel LabelRespostas;
    private javax.swing.JTextArea NomesTextArea;
    private javax.swing.JPanel Painel;
    private javax.swing.JPanel PainelNomes;
    private javax.swing.JTextArea RespostasTextArea;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
